# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bestbud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='purc_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='qtd',
        ),
        migrations.AddField(
            model_name='product',
            name='purchase',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bestbud.Purchase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='qtd',
            field=models.IntegerField(default=0),
        ),
    ]
