# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestbud', '0004_remove_purchase_numberid'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='compra',
            field=models.CharField(default='Compra', max_length=10),
            preserve_default=False,
        ),
    ]
