# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestbud', '0006_auto_20171117_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='id',
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(verbose_name='date purchased'),
        ),
    ]
