# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bestbud', '0007_auto_20171117_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='purchase',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qtd',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_id',
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='produto', to='bestbud.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='qtd',
            field=models.IntegerField(default=1),
        ),
    ]
