# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestbud', '0008_auto_20171117_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='aaa',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
