# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 03:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestbud', '0009_purchase_aaa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='aaa',
        ),
    ]
