# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bestbud', '0011_purchase_aaa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='aaa',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestbud.Product'),
        ),
    ]
