# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestbud', '0012_auto_20171117_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchase_id',
            field=models.IntegerField(default=0),
        ),
    ]
