# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestbud', '0013_purchase_purchase_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='logo',
            field=models.ImageField(default=0, upload_to='static/images'),
            preserve_default=False,
        ),
    ]
