# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestbud', '0021_auto_20171118_0335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='totalprice',
            new_name='total_price',
        ),
    ]
